apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: create-secrets-composer-ai
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: create-secrets-composer-ai
    spec:
      containers:
        - name: create-secrets-redsaia
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              oc wait --for jsonpath='{.status.phase}'=Active ns/composer-ai-gitops
              echo "Read the secret for RH composer ai"
              HF_API_KEY="$(oc extract secret/rh-composer-ai -n openshift-gitops --keys composer-ai-apps-ai-keys-huggingface_apikey --to=-)"
              echo "Create the composer-ai secret in Composer AI Apps project"
              oc delete secret ai-keys -n composer-ai-apps --ignore-not-found
              oc create secret generic ai-keys -n composer-ai-apps --from-literal huggingface_apikey="$HF_API_KEY"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - "ALL"
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
