apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    gitops.ownedBy: cluster-config
  name: cluster-config-app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: patch-me-see-overlays
    repoURL: https://github.com/redhat-composer-ai/cluster-gitops.git
    targetRevision: multi-user
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: cluster-configs
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: user-workload-monitoring
          path: components/cluster-configs/user-workload-monitoring/overlays/default
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: cluster-autoscaling
          path: components/cluster-configs/autoscaling/overlays/default
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        gitops: cluster-config
      name: '{{values.name}}'
    spec:
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      project: cluster-config
      source:
        path: '{{values.path}}'
        repoURL: patch-me-see-clusters-overlays
        targetRevision: patch-me-see-clusters-overlays
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 20m
          limit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: cluster-operators
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: authorino-operator
          path: components/operators/authorino-operator/operator/overlays/managed-services
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: nvidia-gpu-operator
          path: components/operators/gpu-operator-certified/aggregate/overlays/default
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: nfd-operator
          path: components/operators/nfd/aggregate/overlays/default
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-ai-operator
          path: components/operators/openshift-ai/aggregate/overlays/fast-nvidia-gpu
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-pipelines-operator
          path: components/operators/openshift-pipelines/operator/overlays/latest
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-serverless-operator
          path: components/operators/openshift-serverless/operator/overlays/stable
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-servicemesh-operator
          path: components/operators/openshift-servicemesh/operator/overlays/stable
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        gitops: operator
      name: '{{values.name}}'
    spec:
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      project: cluster-config
      source:
        path: '{{values.path}}'
        repoURL: patch-me-see-clusters-overlays
        targetRevision: patch-me-see-clusters-overlays
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 20m
          limit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: tenants
  namespace: openshift-gitops
spec:
  generators:
  - git:
      directories:
      - path: tenants/*/*/overlays/composer-ai-lab
      - path: tenants/*/*/overlays/common
      repoURL: https://github.com/redhat-ai-services/ai-accelerator.git
      revision: main
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        tenant: '{{path[1]}}'
      name: '{{path[1]}}-{{path[2]}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - group: kubeflow.org
        jqPathExpressions:
        - .spec.template.spec.containers[] | select(.name == "oauth-proxy")
        - .spec.template.spec.volumes[] | select(.name == "oauth-config")
        - .spec.template.spec.volumes[] | select(.name == "tls-certificates")
        kind: Notebook
      project: tenants
      source:
        path: '{{path}}'
        plugin:
          name: kustomize-envvar
        repoURL: patch-me-see-clusters-overlays
        targetRevision: patch-me-see-clusters-overlays
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 20m
          limit: 5
