---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-route-url-configmap
  namespace: nvidia-gpu-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-route-url-configmap
rules:
- apiGroups:
  - machine.openshift.io
  resources:
  - machinesets
  verbs:
  - '*'
- apiGroups:
  - autoscaling.openshift.io
  resources:
  - machineautoscalers
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - aws-creds
  verbs:
  - get
  - list
# - nonResourceURLs:
#   - '*'
#   verbs:
#   - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-route-url-configmap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-route-url-configmap
subjects:
  - kind: ServiceAccount
    name: create-route-url-configmap
    namespace: openshift-gitops
