apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openshift-gitops

resources:
  - ./create-route-url-configmap-job/
  - kustomize-envvar-configmap.yaml

patches:
  - path: patch-envvar-sidecar.yaml
    target:
      kind: ArgoCD
