kind: ConfigMap
apiVersion: v1
metadata:
  name: kustomize-envvar
data:
  plugin.yaml: |-
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomize-envvar
    spec:
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build --enable-helm . | perl -pe 's{\\$(\\{)?(\\w+)(?(1)\\})}{$ENV{$2} // $&}ge'"]
