apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
spec:
  repo:
    sidecarContainers:
      - command:
          - /var/run/argocd/argocd-cmp-server
        envFrom:
          - configMapRef:
              name: plugin-substitution-env-vars
        image: 'quay.io/devfile/universal-developer-image:ubi8-latest'
        name: cmp
        resources: {}
        securityContext:
          runAsNonRoot: true
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            name: kustomize-envvar
            subPath: plugin.yaml
    volumes:
      - configMap:
          name: kustomize-envvar
        name: kustomize-envvar
