apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-values.yaml
    target:
      kind: Application
      name: composer-ai-config
      namespace: composer-ai-gitops
