# apiVersion: kustomize.config.k8s.io/v1alpha1
# kind: Component
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - create-route-url-configmap-job.yaml
  - create-route-url-configmap-rbac.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: create-route-url-configmap
    namespace: openshift-gitops
    files:
      - create-route-url-configmap.sh
