apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: composer-ai-lab-argocd
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
          - values:
              user: user1
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      name: 'composer-ai-{{values.user}}-argocd'
      labels:
        tenant: `composer-ai-{{values.user}}`
    spec:
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: composer-ai-{{values.user}}-gitops`
      project: tenants
      source:
        repoURL: 'https://github.com/redhat-composer-ai/cluster-gitops.git'
        path: tenants/composer-ai-lab/argocd/overlays/lab-template
        targetRevision: multi-user
      syncPolicy:
        automated:
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 20m
          limit: 5
