kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: composer-ai-gitops-application-controller-cluster-admin
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: composer-ai-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
